### PR TITLE
Fixed memory editing

### LINKED ISSUE #124: Writing to memory seems to not work correctly
**Description**

It should be possible to select a data cell of the memory inspector, getting it highlighted and then update its value. The highlighting doesn't happen and the same value of the selected cell is sent to the `MemoryProvider` managing the next request.

**How to reproduce:**

A new `EditableMemoryWidget` needs to be created. After that clicking on a data cell of the memory inspector and trying to change its value should make the problem evident. Some debugging might help too.

**Expected behavior**

The data cells should be editable.

**Environment**
 - _OS_: Ubuntu 20.04
 - _Browser_: Chrome 93
 - _Theia Version_: 1.17

**Additional information**

### PR DESCRIPTION
**Pull request by federicobozzini**
#### What it does

This fixes the memory editing. The problem seems to come from some incorrect usage of variables of type `Long`. In short `Long` variables cannot be compared using `===` and cannot be used as key in a `Map`.

This fixes #124 .

#### How to test

An `EditableMemoryWidget` needs to be created. After that a working backend managing the `writeMemory` request needs to exist.

#### Review checklist

- [X] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by colin-grant-work** [comment]
@federicobozzini, thanks for catching these. I was aware that `Long` couldn't be compared with `===`, but it looks like a few still slipped through. I wasn't aware of the problem with using them as keys in a map, so thanks for catching that. Do you have code that would allow this to be tested against a the `cdt-gdb-vscode` DA, or is it only possible to test it against custom code? If so, I can test internally.

**Comment by federicobozzini** [comment]
> Do you have code that would allow this to be tested against a the `cdt-gdb-vscode` DA, or is it only possible to test it against custom code? If so, I can test internally.

Unfortunately our implementation doesn't use the `cdt-gdb-vscode` DA, but a custom DA. A simple way to test could be to have a mock implementation of  the `writeMemory` method checking what is received there.

File: packages/cpp-debug/src/browser/memory-widget/memory-table-widget.tsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ import { MemoryOptionsWidget } from './memory-options-widget';
 import { MemoryHoverRendererService, EasilyMappedObject } from '../utils/memory-hover-renderer';
 import { VariableDecoration, VariableFinder } from '../utils/memory-widget-variable-utils';
 import { MWMoreMemorySelect } from '../utils/memory-widget-components';
-import { MemoryProviderService } from '../memory-provider/memory-provider-service';
+import { hexStrToUnsignedLong } from '../../common/util';
```
Comment (colin-grant-work) [inline packages/cpp-debug/src/browser/memory-widget/memory-table-widget.tsx:32]: Looks like you accidentally removed the import for the memory provider service, so the build is failing.

Comment (federicobozzini) [reply packages/cpp-debug/src/browser/memory-widget/memory-table-widget.tsx:33]: Oopsie, fixed! Thanks.

**Comment by colin-grant-work** [comment]
This appears to be working well. I was able to write to memory successfully, and the writes were accepted and executed by the GDB backend.

One thing I noticed while testing this code is that it looks like one `memoryRightRequest` is being sent for every 8-bit-byte edited. I had a region that started as `0000 0000` (two 16-bit-words), and I made a request to change it to `0102 0304`. The intent is that that should send two requests, one for each word, but in fact four were made:

image

Somewhere in this code, there should be a check for whether a `pendingEdit` is included in one of the edits already submitted, and it should be deleted from the map early if so.

**Comment by colin-grant-work** [comment]
On a second look, I think probably the problem is the `new Set<Long>()` idea. If they can't be keys of `Map`s, then they also can't be members of `Set`s....

**Review by colin-grant-work — APPROVED** [review]
This looks good to me and doesn't send more requests than intended.

**Comment by colin-grant-work** [comment]
@federicobozzini, it looks like merging your styling PR has introduced some conflicts with this PR - would you mind rebasing this so it can be merged?

**Comment by federicobozzini** [comment]
@colin-grant-work The rebase should be ready.
